### ISSUE TITLE
大佬有否计划增加每天定时使用加速卡 收取能量？

### ISSUE THREAD

**Issue by uwhatsup** [Fansirsqi/Sesame-TK#15]
### 增强类型

功能型增强

### 具体描述

大佬有否计划增加每天定时使用加速卡 收取能量？

**Comment by Fansirsqi** [comment]
你觉得本模块使用到该功能的场景是哪些？
请尽可能的列举…

**Comment by amulin202** [comment]
就是开挂偷别人的，还不允许被别人偷，跟保护罩一样意思。

**Comment by Fansirsqi** [comment]
> 就是开挂偷别人的，还不允许被别人偷，跟保护罩一样意思。

模块已经有了一天一用能量保护罩功能

自己的罩住了，别人应该偷不到，可能暂时不会加入该功能~可能

**Comment by Fansirsqi** [comment]
@loool-com 这位大佬已经为模块加上啦，能不能用还没试过呜呜呜~😭
