### ISSUE TITLE
每日签到/农场/新村 功能不生效

### ISSUE THREAD

**Issue by SingleCoreSun** [Fansirsqi/Sesame-TK#18]
### 程序版本 / 框架版本 / 模块版本

ZFB版本：10.5.88.8000 框架版本：LSPosed 7075 模块版本：t24.11.29.alpha

### 系统版本 / Android版本

RedMagicOS 9.5.19 安卓14

### 详细描述问题发生的具体原因

**森林、庄园、新村等功能总开关打开**，
只有森林功能正常，森林记录中存在正常日志；
庄园功能不生效，庄园记录中没有任何日志；
蚂蚁新村功能不生效，全部记录中无日志。

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

12:05:12.734 runtime: 加载UI配置
12:05:12.741 runtime: FileUtil, [statistics]读:true;写:true
12:05:14.726 runtime: Config, 开始加载配置
12:05:14.726 runtime: 加载配置: 热心市民孙先生
12:05:14.736 runtime: Config, 加载配置结束
12:05:15.338 runtime: 加载UI配置
12:05:15.343 runtime: FileUtil, [statistics]读:true;写:true
12:05:20.050 runtime: ApplicationHook, hook matchVersion successfully
12:05:20.051 runtime: ApplicationHook, hook login successfully
12:05:20.051 runtime: ApplicationHook, hook service onCreate successfully
12:05:20.051 runtime: ApplicationHook, hook MiscUtils successfully
12:05:20.051 runtime: ApplicationHook, load success: com.eg.android.AlipayGphone
12:05:20.189 runtime: ApplicationHook, Activity onResume
12:05:20.276 runtime: ApplicationHook, Service onCreate
12:05:20.278 runtime: ApplicationHook, hook registerBroadcastReceiver successfully
12:05:20.279 runtime: FileUtil, [statistics]读:true;写:true
12:05:20.358 runtime: 模块版本：24.11.29.alpha.18.31.52
12:05:20.358 runtime: 开始加载
12:05:20.358 runtime: Config, 开始加载配置
12:05:20.358 runtime: 加载配置: 2088512052477632
12:05:20.379 runtime: Config, 格式化配置: 2088512052477632
12:05:20.380 runtime: Config, 加载配置结束
12:05:20.412 runtime: NewRpcBridge, 成功获取新的 RPC 调用方法
12:05:20.414 runtime: 取消定时唤醒:0|000000
12:05:20.414 runtime: setAlarmTask triggerAtMillis:2024-12-05 00:00:00 operation:PendingIntent{f78bf74: android.os.BinderProxy@8770c9d}
12:05:20.414 runtime: 设置定时唤醒:0|000000
12:05:20.415 runtime: setAlarmTask triggerAtMillis:2024-12-04 12:50:00 operation:PendingIntent{ef66512: android.os.BinderProxy@fa0b4e3}
12:05:20.415 runtime: 设置定时唤醒:1|1250
12:05:20.415 runtime: setAlarmTask triggerAtMillis:2024-12-04 23:50:00 operation:PendingIntent{91c5ee0: android.os.BinderProxy@73cd599}
12:05:20.415 runtime: 设置定时唤醒:2|2350
12:05:20.418 runtime: AntSports, hook readDailyStep successfully
12:05:20.428 runtime: FileUtil, [statistics]读:true;写:true
12:05:20.429 runtime: 加载完成
12:05:20.441 runtime: 应用版本：10.5.88.8000
12:05:20.441 runtime: 模块版本：24.11.29.alpha.18.31.52
12:05:20.441 runtime: 开始执行
12:05:20.449 runtime: FileUtil, [statistics]读:true;写:true
12:05:21.624 runtime: 执行开始-蚂蚁森林
12:05:22.119 runtime: 服务器时间：12:05:22，本地与服务器时间差：-0秒
12:05:22.119 runtime: 进入[热心市民孙先生|*]的蚂蚁森林
12:05:22.119 runtime: 获取[我]主页成功01733285122119
12:05:23.295 runtime: 服务器时间：12:05:23，本地与服务器时间差：-0秒
12:05:23.295 runtime: 进入[-|]的蚂蚁森林
12:05:23.295 runtime: [-|]被能量罩保护着哟
12:05:24.006 runtime: 执行结束-蚂蚁森林
12:05:24.010 runtime: FileUtil, [statistics]读:true;写:true
12:05:25.067 runtime: 加载UI配置
12:05:25.083 runtime: FileUtil, [statistics]读:true;写:true
12:06:14.373 runtime: 加载UI配置
12:06:14.380 runtime: FileUtil, [statistics]读:true;写:true
12:06:18.207 runtime: HtmlViewerActivity, URI path: /storage/emulated/0/Android/media/com.eg.android.AlipayGphone/sesame/log/runtime.2024-12-04.log

</code></pre></details>

**Comment by Fansirsqi** [comment]
方便的话请提供下你账号的`config_v2.json`配置中的`AntFarm`对象
文件路径`/storage/emulated/0/Android/media/com.eg.android.AlipayGphone/sesame/config/UID/config_v2.json`
```json
"AntFarm":{
  ...
}
```

**Comment by SingleCoreSun** [comment]
> 方便的话请提供下你账号的`config_v2.json`配置中的`AntFarm`对象 文件路径`/storage/emulated/0/Android/media/com.eg.android.AlipayGphone/sesame/config/UID/config_v2.json`
> 
> ```json
> "AntFarm":{
>   ...
> }
> ```

```
```
