### ISSUE TITLE
悬浮通知希望能改回统计

### ISSUE THREAD

**Issue by Maozai-Teng** [Fansirsqi/Sesame-TK#24]
### 增强类型

功能型增强

### 具体描述

之前悬浮通知，只要运行成功就显示本次记录统计，什么收取多少，浇水多少……
现在好像一直只显示施工时间和下次时间，对我来说这个完全是无用信息…希望可以改成之前那种统计信息(或者给个选项，让用户选择显示什么)
![IMG_20241205_141004](https://github.com/user-attachments/assets/b93c5426-7aaf-4b85-99cf-9e1bcf552975)

**Comment by Fansirsqi** [comment]
应该是系统对通知做了的定制化吧
这是我现在的样子
<details><summary>【原生样式】展开查看</summary><pre><code>

![1733382670852](https://github.com/user-attachments/assets/cccaaea7-620f-4e8b-a1be-f14555fe3c76)

</code></pre></details>

<details><summary>【非原生样式】展开查看</summary><pre><code>

![1733382670856](https://github.com/user-attachments/assets/2299a0e4-e3bd-4ee8-951a-ec084dc46e5b)

</code></pre></details>

**Comment by Maozai-Teng** [comment]
> 应该是系统对通知做了的定制化吧 这是我现在的样子
> 
> 【原生样式】展开查看
> 【非原生样式】展开查看

Emmm…那可能是我系统的问题_(:3」 ∠）_……安卓10，MIUI 12.5，默认只能显示2行…第三行变成后面的点点点了

**Comment by Fansirsqi** [comment]
> > 应该是系统对通知做了的定制化吧 这是我现在的样子
> > 【原生样式】展开查看
> > 【非原生样式】展开查看
> 
> Emmm…那可能是我系统的问题_(:3」 ∠）_……安卓10，MIUI 12.5，默认只能显示2行…第三行变成后面的点点点了

把通知样式改成原生样式

**Comment by Maozai-Teng** [comment]
> > > 应该是系统对通知做了的定制化吧 这是我现在的样子
> > > 【原生样式】展开查看
> > > 【非原生样式】展开查看
> > 
> > 
> > Emmm…那可能是我系统的问题_(:3」 ∠）_……安卓10，MIUI 12.5，默认只能显示2行…第三行变成后面的点点点了
> 
> 把通知样式改成原生样式

![E5 %4EM6~{7E}6SC9}~NZ{5](https://github.com/user-attachments/assets/7e6a7b8a-0370-4602-a3e3-8463d14eb3f6)

没啥用，甚至更丑了，可能是因为我这边主题限制，让提示只能显示两行的原因。
其实我觉得可以优化一下形态，把收/帮统计放最上面，或者改成更简洁的提示，两行就把内容全部表达出来。
“上次施工时间”和“下次施工时间”就有10个字重复冗杂，其实不太美观却又占用了宝贵的UI空间，看看怎么样精简美观一下_(:3」 ∠）_
