### ISSUE TITLE
1204版本签名好像有问题

### ISSUE THREAD

**Issue by zhangyibin8111** [Fansirsqi/Sesame-TK#26]
### 程序版本 / 框架版本 / 模块版本

程序：10.6.58.9100，LSPosed：1.8.6，模块：24.11.29

### 系统版本 / Android版本

Android 10

### 详细描述问题发生的具体原因

1204版本签名好像有问题，不能覆盖安装

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(此处粘贴问题 Log)

</code></pre></details>

**Comment by Fansirsqi** [comment]
卸载后重新安装，签名问题可能是调整SDK导致的，具体我也不清楚，卸载不会影响原来的数据
