### ISSUE TITLE
在Hyper OS 2无法检测到正确的“始终在后台运行”权限

### ISSUE THREAD

**Issue by Xiaodu233** [Fansirsqi/Sesame-TK#32]
### 程序版本 / 框架版本 / 模块版本

0.1.0-release

### 系统版本 / Android版本

Hyper OS 2 Android 15

### 详细描述问题发生的具体原因

似乎是更新到最近两天的版本后，芝麻粒无法正确检测始终在后台运行权限，一打开支付宝就跳转到省电策略，即使调整到无限制也还是一直跳转，无法正常使用。

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

22:50:35.271 支付宝无始终在后台运行权限

</code></pre></details>

**Comment by Fansirsqi** [comment]
可能是你的电量和性能app定制过或者其他app修改了支付宝常驻后台
每次跳转到省电策略即使你调整成无限制但是，下一次弹开来他还是默认的？

**Comment by Xiaodu233** [comment]
有点奇怪，我关掉模块，清除了两个应用数据，用了快一天，现在打开模块又正常了，省电策略改成智能限制也没有影响。

**Comment by Fansirsqi** [comment]
无后台权限不是必要设置，模块会随你打开支付宝启动，重启支付宝时启动

**Comment by bocchi810** [comment]
@bocchi810 我感觉HyperOS2是魔改了安卓的什么导致了这个Issue,我也出现了这种情况

**Comment by acooler15** [comment]
小米13 ,os 2.0.200.9，芝麻粒最新版，支付宝10.6.66.8000 没有遇到此问题。
