### ISSUE TITLE
没有会员签到功能

### ISSUE THREAD

**Issue by zaq7434** [Fansirsqi/Sesame-TK#39]
### 程序版本 / 框架版本 / 模块版本

lspatch

### 系统版本 / Android版本

11

### 详细描述问题发生的具体原因

以前的1.3版本在有如下任务。开关应该是设置->其他->领取积分

00:06:45 会员任务🎖️[滑动浏览15秒红包会场]#3积分
00:06:47 会员任务🎖️[逛年度好运拿红包]#3积分
00:06:48 会员任务🎖️[逛15秒精选超值好物]#3积分
00:06:50 会员任务🎖️[逛一逛蚂蚁新村]#3积分
00:06:52 会员任务🎖️[逛一逛滴滴出行小程序]#3积分
00:06:54 会员任务🎖️[逛15秒支付宝新型钱包]#5积分
00:06:55 会员任务🎖️[逛热卖好货15秒]#3积分
00:06:57 会员任务🎖️[看15秒视频领积分]#5积分
00:06:59 会员任务🎖️[逛一逛芝麻信用]#3积分
00:07:00 会员任务🎖️[逛蚂蚁保领森林福利]#3积分
00:07:03 会员任务🎖️[逛15秒精选超值好物]#3积分
00:07:05 会员任务🎖️[逛热卖好货15秒]#3积分
00:07:07 会员任务🎖️[滑动浏览优品会场15秒]#3积分
00:07:08 会员任务🎖️[看15秒视频领积分]#5积分
00:07:10 会员任务🎖️[滑动浏览15秒红包会场]#3积分
00:07:13 会员任务🎖️[滑动浏览优品会场15秒]#3积分
00:07:15 会员任务🎖️[逛15秒精选超值好物]#3积分
00:07:16 会员任务🎖️[逛热卖好货15秒]#3积分
00:07:18 会员任务🎖️[滑动浏览15秒红包会场]#3积分
00:07:21 会员任务🎖️[滑动浏览15秒红包会场]#3积分
00:07:23 会员任务🎖️[滑动浏览优品会场15秒]#3积分
00:07:25 会员任务🎖️[滑动浏览优品会场15秒]#3积分
00:07:27 会员任务🎖️[滑动浏览15秒红包会场]#3积

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(此处粘贴问题 Log)
无

</code></pre></details>

**Comment by magisk317** [comment]
@zaq7434 有搞头，看能不能把代码复制过来，顺便测试下 tg 回复 github

**Comment by Fansirsqi** [comment]
代码在，好像不太管用，没看具体实现

**Comment by zaq7434** [comment]
> 代码在，好像不太管用，没看具体实现

是不是有开关控制？因为我现在用老版本还能做。就是会弹验证。所以才来换新版本。

**Comment by zaq7434** [comment]
点关闭了。。晕

**Comment by zaq7434** [comment]
如何重新开启？
